language: ruby
services: "-postgresql"
bundler_args: "--without development --deployment"
cache: bundler
before_script:
- cp config/database.travis.yml config/database.yml
- bundle exec rake db:setup
script:
- bundle exec rspec spec/
env:
  global:
  - secure: 0OpGMjkQ1yGuNx2HYCMPV2n+quWy+5lhZQf/40lnHItXfbnHUioZjgDxHHhz7/TLu5Bub0LtqE0dhvY/c+s6GIfRUaxkwhxRgA9kjj+RVyvlfpKgqHyMAhEsLL68iXdytdPFBZm0Zh7I3SeeTBOSSvPM6UmDfvZZR/7H/aufLjT4Lb4P/Wek7nK8UwtG29X+MqC22Dc6j5MxFa38mifzhiNl/STxMbsMd3vTgs6wbia1hWVik/UQLegQ8tbE26d+K9r0dBomRUtlXkJRQBFjxsR82FM+M0NaF39eZoAK10F3itT+6ko0dGirzoXnK0N6bJjl5Mfy8RaRdLst4BJSfD7k5BWaLj4wqD+EpdcDQI+Wf2ZPZaiR9aLHkVVTR8oPDNp8M6cQUZJd0EP8XcWneZp3QMgD6IdsQ/S+xOHjtAoO8usxDGQpVhqXF1vhimN67oadzsEGQNpw2UfmtJFBQPLgPDF/v0VkN4qn3dEbhvTiMQzPyKmItqNaDVdUMM2XjGRkf6yIwPatgSPIjS/X6+DDax7rO0ADi5kxBJTc3THXZVMpPtAPH0foTIEWnPTbCuAJaqSzKSatxOeJwMbmes6tG4a1TtgMWx2JzYG/LSGMkpPAyZ6jiX2xBFZCPPdVh19DpVGXuiRiUMREMvI3mZfctxfKMFrurPeawzTp2sA=
deploy:
  provider: heroku
  api_key:
    secure: pFfnRcsOiOqrpXsaKS2sNq81zV+LL9G56pHEsTaBLqd7XUWKaAQh4z7/DdmZPacE98LmMOJR/trqABehSES0X3QfIUamnaqfSLiYZmjzO3aotR0TVu3CiaExAF57SRNVbn4JMuouO3+Vwfji69GWIaBnko9SAtjWlxROwkQbNeEgn9PXE9jUNJrgCAoaya7QUYqun7K8zATerVFS97kc6NgnHfNhf6132VYWtDh5HR+rppBK8fJty0g0aNe+akb81hEbBNkmz8rCgjtchwy0A7ubgkpxpd6AqPMY0FGZnosazKPDrVY/MJM5VYZv4QISJ9Mr+E7vz3P9lwiLaTR8j7DaWwEkFo78+RJVNifefVgoMnerZ4syqFe+VfZ4dzT/hMgI/WvrKQdvCanw23Dh6o6IzA3OiOziQEx+/Cx7NzO5u+nOJWzW5GbBTsYA79CZ9TiFMr0BBgGaJS9qhd8PxlPOlb8nmEdt5+Fb2pZCoPyvaY4xZfOmyS/JG8D0FcB+slfosOFZ69IjB7fxjvA/+4L78Uua1djGtzrhnGba597BW0IxDGVZcvEOSF7SqvJwBONg3jp4ddgbwGd7r0a7k1zS96lcxgLU25yy5ZZJO7SSPxyfMmOwKma/MH6PZlPwk1G+HYzHwTw66iyX/cOMZeWls+6aG/cyq4Trfpz+8lk=
  app: github-activity-watcher
  on:
    repo: chubachi-pt-2017/activity_watcher-2
  run:
  - bundle exec rake db:migrate
